"""assets, ohlcv_candles hypertable, news_articles

Revision ID: 0001
Revises:
Create Date: 2026-05-19 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ARRAY, UUID

from alembic import op

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ── 1. Extension (non-autogenerated) ──────────────────────────────────────
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")

    # ── assets ────────────────────────────────────────────────────────────────
    op.create_table(
        "assets",
        sa.Column(
            "id",
            UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("symbol", sa.Text(), unique=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("asset_type", sa.Text(), nullable=False),
        sa.Column("exchange", sa.Text(), nullable=False),
        sa.Column("currency", sa.Text(), nullable=False),
        sa.Column("sector", sa.Text(), nullable=True),
        sa.Column("industry", sa.Text(), nullable=True),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, server_default=sa.text("TRUE")
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )
    op.create_index("idx_assets_symbol", "assets", ["symbol"])
    op.create_index("idx_assets_type", "assets", ["asset_type"])

    # ── ohlcv_candles ─────────────────────────────────────────────────────────
    op.create_table(
        "ohlcv_candles",
        sa.Column("time", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "asset_id",
            UUID(as_uuid=True),
            sa.ForeignKey("assets.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("timeframe", sa.Text(), nullable=False),
        sa.Column("open", sa.Numeric(20, 8), nullable=False),
        sa.Column("high", sa.Numeric(20, 8), nullable=False),
        sa.Column("low", sa.Numeric(20, 8), nullable=False),
        sa.Column("close", sa.Numeric(20, 8), nullable=False),
        sa.Column("volume", sa.Numeric(28, 8), nullable=False),
        sa.Column("vwap", sa.Numeric(20, 8), nullable=True),
        sa.Column("trade_count", sa.Integer(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("time", "asset_id", "timeframe"),
    )

    # ── 2. Hypertable (non-autogenerated) ─────────────────────────────────────
    op.execute("SELECT create_hypertable('ohlcv_candles', 'time')")

    # ── 3. Compression config (non-autogenerated) ─────────────────────────────
    op.execute(
        "ALTER TABLE ohlcv_candles SET ("
        "timescaledb.compress, "
        "timescaledb.compress_segmentby = 'asset_id, timeframe'"
        ")"
    )

    # ── 4. Compression policy (non-autogenerated) ─────────────────────────────
    op.execute("SELECT add_compression_policy('ohlcv_candles', INTERVAL '7 days')")

    # ── Indexes on ohlcv_candles ───────────────────────────────────────────────
    op.create_index("idx_candles_asset_time", "ohlcv_candles", ["asset_id", sa.text("time DESC")])

    # ── news_articles ─────────────────────────────────────────────────────────
    op.create_table(
        "news_articles",
        sa.Column(
            "id",
            UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("published_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("sentiment_score", sa.Numeric(5, 4), nullable=True),
        sa.Column("symbols", ARRAY(sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("NOW()"),
        ),
    )
    op.create_index(
        "idx_news_published", "news_articles", [sa.text("published_at DESC")]
    )
    op.create_index(
        "idx_news_symbols", "news_articles", ["symbols"], postgresql_using="gin"
    )


def downgrade() -> None:
    op.drop_index("idx_news_symbols", table_name="news_articles")
    op.drop_index("idx_news_published", table_name="news_articles")
    op.drop_table("news_articles")

    # Compression policy and hypertable are dropped with the table
    op.drop_index("idx_candles_asset_time", table_name="ohlcv_candles")
    op.drop_table("ohlcv_candles")

    op.drop_index("idx_assets_type", table_name="assets")
    op.drop_index("idx_assets_symbol", table_name="assets")
    op.drop_table("assets")
